---
title: "Referencias"
---

<font size = "6">
<center>
**El Autor**
</center>
</font>

**[1]** V. Moreno, M. Ramírez, C. de la Oliva y E. Moreno. "Biografía de Stephen King (Su vida, historia, bio resumida)". Biografía de personajes históricos y celebridades. Enciclopedia biográfica. https://www.buscabiografias.com/biografia/verDetalle/1523/Stephen%20King.
ㅤ    
ㅤ   
**[2]** E. Castillo. "Stephen King: Libros y biografía autor". Lecturalia. https://www.lecturalia.com/autor/358/stephen-king.
ㅤ    
ㅤ   
**[3]** N. Ceballos. "Stephen King para principiantes". GQ España. https://www.revistagq.com/noticias/cultura/articulos/stephen-king-para-principiantes-libros/33429.
ㅤ
<font size = "6">
<center>
**El Resplandor**
</center>
</font>

**[4]** Equipo Biblioteca Salvadora. "El resplandor - Stephen King (Resumen completo, análisis y reseña) - Biblioteca Salvadora | Descargar PDF". Biblioteca Salvadora. https://bibliotecasalvadora.com/el-resplandor-stephen-king-resumen-completo-analisis-y-resena/.
ㅤ    
ㅤ   
**[5]** "The Shining Danny Torrance Writing GIF | GIFDB.com". GIFDB.com. https://gifdb.com/gif/the-shining-danny-torrance-writing-fidp4d866v1nsboj.html.
ㅤ    
ㅤ   
**[6]** Anonymous. "Beaufort Place GIF | Gfycat". Gfycat. https://gfycat.com/miserlyesteemedhypsilophodon.
ㅤ    
ㅤ   
**[7]** Administrador de Esta Es La Historia. "Libro El Resplandor Del Escritor Stephen King". Esta Es La Historia. https://estaeslahistoria.com/c-ficcion/el-resplandor-libro/#Conoces_los_Personajes_en_El_Resplandor_Libro.
ㅤ    
ㅤ   
**[8]** J. Paur. "DOCTOR SLEEP Director Mike Flanagan Still Hopes to Make His Dick Hallorann Spinoff Film — GeekTyrant". GeekTyrant. https://geektyrant.com/news/doctor-sleep-director-mike-flanagan-still-hopes-to-make-his-dick-hallorann-spinoff-film.
ㅤ    
ㅤ   


<font size = "6">
<center>
**Doctor Sueño**
</center>
</font>

**[9]** S. King, Doctor sueño. Barcelona, Spain: Plaza y Janés, 2013.
ㅤ    
ㅤ   
**[10]** Equipo SuperSummary. "Doctor Sleep Summary". SuperSummary. https://www.supersummary.com/doctor-sleep/summary/.
ㅤ    
ㅤ   
**[11]** Belial2412. "Doctor Sleep a movie that is great". PeakD. https://peakd.com/hive-166847/@belial2412/doctor-sueno-una-pelicula-que-es-genialdoctor-sleep-a-movie-that-is-great-esp-eng.
ㅤ    
ㅤ   
**[12]** Warner Bros. Pictures. STEPHEN KING'S DOCTOR SLEEP - Final Trailer [HD]. (8 de septiembre de 2019). [Video en línea]. Disponible: https://www.youtube.com/watch?v=BOzFZxB-8cw

**[13]** J. Jovial. "Doctor Sleep (2019) | 31 Days of Horror: Oct 18". RetroZap. https://www.retrozap.com/doctor-sleep-2019-31-days-of-horror-oct-18/.

**[14]** Nullmu Studio. "Doctor Sleep 2019: Rose The Hat Gif". FetcherX. https://fetcherx.com/post/tumblr/636443120535502848?search=flanagan.

**[15]** Warner Bros. Entertainment. Doctor Sleep | "Here's The Deal" Clip | Warner Bros. Entertainment. (10 de enero de 2020). [Video en línea]. Disponible: https://www.youtube.com/watch?v=IO9RKfpyAfo

**[16]** Tumpik. "Doctor Sleep gifs | Explore Tumblr Posts and Blogs | Tumpik". Tumblr Online Web Viewer and Statistics | Tumpik. https://www.tumpik.com/tag/doctor%20sleep%20gifs.

**[17]** Cuentapalabras. (s. f.). Análisis de sentimientos aplicado a la literatura | Cuentapalabras. Archivo Iberoamericano de Cetrería - Universidad de Valladolid. http://www.aic.uva.es/cuentapalabras/análisis-de-sentimientos-aplicado-a-la-literatura.html#primeros-análisis






























