
<center>
# **El Autor**
</center>



<font size = "4">

Nacido el **21 de septiembre de 1947** en Portland, Maine, asitió a la 
universidad de la ciudad y temrinó sus estudios en 1970. A los 2 años su padres
se separaron y fue criado junto a su hermano mayor por su madre [1].


A los **7 años** escribió su primer relato y a los **18 años** vendió su primer 
texto a una revista. En 1973 publicó su primera novela, **"Carrie"**, que fue un
éxito inmediato pues vendió 4 millones de copias y 2 años después fue adaptada
a la gran pantalla [1].


Sus siguientes obras fueron **"Salem's Lot"** en 1975 y **The Shining** o **El
Resplandor** en español de 1977 que también fue adaptada a cine en 1980 por el
famoso director Stanley Kubrick. Podo después escribió otras populares obras
como The Stand (Apocalipsis, 1978), The Dead Zone (La Zona Muerta, 1979, 
Firestarter (Ojos de fuego, 1980), Cujo (1981), Christine (1983, filmada 1983), 
It (Eso, 1986), Misery (1987) y The Tommyknockers (1987) de las cuales muchas
fueron adaptadas a cine y a televisión [1].



![Stephen King [3]](https://media.revistagq.com/photos/61570a778052a49b36a0342f/16:9/w_2560%2Cc_limit/GettyImages-131859459%2520(1).jpg)



Con la duda de si sus libros eran éxitos por su nombre o por su calidad decidió
escribir algunas obras bajo el pseudónimo de **"Richard Bachman"**


El *19 de junio de 1999* fue atropellado cuando paseaba cerca de su casa y tuvo
que ser sometido a 5 cirugías y tuvo que estar semanas hospitalizado por su
grave estado de salud. Ese mismo año terminó su obra **From a Buick 8** que
trata de un vehículo paranormal e incluyo su vivencia en algunos aspectos de la
saga **La Torre Oscura** [2].


Desde 1971 está casado con la novelista **Tabitha King** y es padre de dos 
hijos [1].



</font>