<center>
# **El Resplandor**


> **Caja de Seguridad**    
> *El segundo día de diciembre de un año en el que un cultivador de cacahuates de Georgia hacía negocios en la Casa Blanca, uno de los hoteles de verano más importantes de Colorado ardió hasta los cimientos. El Overlook fue declarado siniestro total.* [9, p. 13]

</center>


<font size = "4">

**Doctor Sueño** de 2013 es la secuela de **El Resplandor** y abarca la vida de
Danny Torrance quien ahora tiene 40 años y tiene problema de alcoholismo. Vaga
por Estados Unidos y escapa de los fantasmas que ve bebiendo, pero un día se
muda a Frazier, un pequeño pueblo de New Hampshire, en donde decide unirse a
Alcoholicos Anónimos, consigue un diferentes trabajos, entre ellos el de cuidados
paliativos en donde consigue el apodo de **"Doctor Sueño"** y sobre todo, conoce
a Abby [10].

<center>
![Doctor Sleep (Warner Bros. Pictures 2019) [11]](https://images.hive.blog/p/x7L2VSNEiyAB5Ux7nxKmLo6yLyEJT6Jt5yhNCUpGN3PuDX8fNCQbJSUzMjz3arNpGcGpr8nK14UXGTf?format=match&mode=fit){width=150% height=150%}
</center>





<font size = "6">
**Personajes**    
</font>
ㅤ  

<font size = "5">
*Daniel Torrance* 
</font>


Varias decadas después, Danny ha crecido para convertirse en un hombre que escapa
del "resplandor" bebiendo y vagando por todo el país. Después de una experiencia
con un bebé de una mujer con la que se acostó decidió recapacitar y varios meses
luego logró dejar de beber a diario. Al mudarse a Frazier logra contactarse con
**Abby** y se hace amigo de **Billy Freeman** [9].


<center>
![Danny Torrence [12]](https://s1.dmcdn.net/v/RIZwI1VbNotrwxT17/x1080){width=150% height=150%}
</center>





<font size = "5">
*Abra Rafaela Stone* 
</font>


Hija de Lucy y David Stone,  vive en Anninston, New Hampshire. Abby es una 
niña/adolescente que tiene un "resplandor" muy fuerte, incluso más que el 
"resplandor" de Danny y casi desde su nacimiento tiene una conexión psíquica con
él pero tiene comunicación completa hasta que él se muda a Frazier y empíeza a 
llamarlo "tío" [9].


<center>
![Abby Stone habla mentalmente con Danny [12]](https://legendary-digital-network-assets.s3.amazonaws.com/wp-content/uploads/2019/10/13073145/Doctor-Sleep-Abra.jpg){width=150% height=150%}
</center>





<font size = "5">
*Billy Freeman* 
</font>


El amigo que Danny conoce al llegar a Frazier, el encargado del mantenimiento
municipal y quién da a Dann y su primer trabajo y lo lleva al grupo de Alcoholicos
Anónimos. Él también tiene el "resplandor" en mucha menor medida que Danny pero
desconocía su posesión [9].


<center>
![Billy Freeman conoce a Danny [12]](https://filmschoolrejects.com/wp-content/uploads/2019/09/Doctor-Sleep-11-1.jpg){width=150% height=150%}
</center>





<font size = "5">
*True Knot / El Nudo Verdadero* 
</font>


Son un grupo de personas sobrenaturales que ha vivido cientos de años, han
recorrido todo el mundo alimentandose del "vapor" que extraen torturando
y asesinando a las personas con el "resplandor", principalmente de niños que
secuestran. Viajan en caravanas en sus casas rodantes. Los principales miembros
son [9]:

+ Rose la Chistera: La Líder.
+ Papá Cuervo: El amante de Rose la Chistera.
+ Abuelo Flick.
+ Barry el Chino.
+ Andi Colmillo de Serpiente.
+ Sarey La Callada.
+ Jimmy el Números.


<center>
![Miembros del Nudo Verdadero [13]](https://www.retrozap.com/wp-content/uploads/2020/10/31DaysOfHorror20-18_DoctorSleep-03.jpg){width=150% height=150%}
</center>
















