
<center>
# **El Resplandor**


> **REDRUM**    
> *Esa es la palabra que Danny había visto en el espejo. Y, aunque no sabía leer, entendió que era un mensaje de horror.*

</center>



<font size = "4">

"El Resplandor" de 1977 es la tercera obra del maestro del terror, Stephen King [1].


<center>
![Stephen King [3]](https://media.giphy.com/media/l41YuwS5IipGquPmM/giphy.gif){width=150% height=150%}
</center>

<font size = "6">
**Personajes**    
</font>
ㅤ    
<font size = "5">
*Danny Torrance* 
</font>

El pequeño hijo de Jack y Wendy Torrance, tiene *"el resplandor"*, un don que le
permite ver el pasado, conocer el futuro y comunicarse con los muertos. Su 
resplandor lo converte en el objetivo del Hotel Overlook quién usa a su padre 
para tomarlo [4].

<center>
![The Shining Danny Torrance Writing [5]](https://gifdb.com/images/high/the-shining-danny-torrance-writing-fidp4d866v1nsboj.gif){width=150% height=150%}
</center>





<font size = "5">
*Jack Torrance* 
</font>

Siendo escritor y habiendo sido despedido su empleo como profesor por golpear a
un estudiante luego de un ataque de ira, Jack Torrance decide salva a su familia
y alejarse del alcohol aceptando el trabajo de cuidador del aislado y solitario
Hotal Overlook pensando también en retomar sus escritos, pero los oscuros entes
que acechan lo incitan a asesinar a su familia [4].





<font size = "5">
*Wendy Torrance* 
</font>

Después de que su familia casi fue destruída por el alcohol, decide apoyar a su
esposo en su proceso de rehabilitación, pero no estaba preparada para tener que
luchar contra él para salvar su vida y la de su pequeo hijo [4].


<center>
![Jack & Wendy [6]](https://thumbs.gfycat.com/MiserlyEsteemedHypsilophodon-size_restricted.gif){width=150% height=150%}
</center>





<font size = "5">
*El Hotel Overlook* 
</font>

>  *"Tras una fachada de ensueño, entre majestuosos paisajes y absoluta tranquilidad, el hotel Overlook muestra vida propia, esta entidad maligna posee habilidades psíquicas a través de las cuales logra controlar a todos los fantasmas y la mente personas que habitan en él."*[7]

<center>
!["El Gran Hotel Overlook" [7]](https://www.looper.com/img/gallery/what-the-hotel-from-the-shining-looks-like-today/aint-life-grand-at-the-overlook-1545688581.jpg){width=150% height=150%}
</center>





<font size = "5">
*Dick Halloran* 
</font>

El cocinero del Hotel y el mayor aliado de Danny, le enseña que él comparte el
don del **resplandor**. Él le advierte de los secretos del Hotel pero le enseña
que no pueden hacerle daño.

<center>
![Dick Halloran en Doctor Sueño [8]](https://images.squarespace-cdn.com/content/v1/51b3dc8ee4b051b96ceb10de/1594222851371-IMCGD7I3G46HC0UQIOWT/image-asset.jpeg){width=150% height=150%}
</center>





<font size = "5">
*Acontecimientos* 
</font>

1- Jack es despedido por golpear al alumno que pinchó las ruedas de su auto.
ㅤ    
ㅤ   
2- Jack acepta la propuesta de trabajo de su amigo Albert Shockley viendo la 
oportunidad de alejarse del alcohol, recuperar su relación con su familia y
terminar su novela.
ㅤ    
ㅤ   
3- El Sr. Ullman no está de acuerdo en contratar a Jack conociendo sus problemas
de ira y alcoholismo y recordando que el anterior cuidador enloqueció y asesinó
a sus dos hijas y esposa para luego suicidarse.
ㅤ    
ㅤ   
4- Jack insiste y es contratado. El señor Ullman le enseña el funcionamiento de
la caldera y el peligro de no liberar la presión manualmente cada cierta cantidad
de tiempo.
ㅤ    
ㅤ   
5- Danny conoce a Dick Halloran y este, telepaticamente, le cuenta que comparte
el mismo don que su abuela llamaba "el resplandor". Además, le dice que las
cosas del Hotel no pueden lastimarlo pero que debe alejarse de  la **habitación
"237"**. Antes de irse le recuerda que en cualquier momento podría comunicarse
con él por ayuda.
ㅤ    
ㅤ   
6- Danny empieza tener visiones del pasado y del futuro pero recordando el 
mensaje de Dick decide no darles importanci y solo huir de ellas.
ㅤ    
ㅤ   
7- El Hotel no puede tomar a Danny así que decide hacerlo mediante su padre,
Jack.
ㅤ    
ㅤ   
8- Jack empieza a tener pesadillas en las que asesina a su esposa e hijo, queda
en estado de trance y tiene charlas con los fantasmas del lugar, incluyendo a 
la mujer de la habitación 237.
ㅤ    
ㅤ   
9- El Hotel posee por completo a Jack y en un primer ataque con un mazo Wendy 
logra defenderse, ataca con un cuchillo a Jack y lo encierra en la gran despensa
pero no antes de que Jack le partiera unas costillas con el mazo.
ㅤ    
ㅤ   
10- Wendy corre y con Danny intenta escapar y pedir ayuda pero Jack había
destruído la moto de nieve y cortado los cables de las ocmunicaciones.
ㅤ    
ㅤ   
11- Wendy se esconde con Danny en un baño mientras el fantasma de Delbert Grady,
el antigüo cuidador lo libera y Jack empieza a buscarlos de nuevo. Poco tiempo
antes, Danny contactó a Dick que se encontraba en Florida y este emprende el 
viaje para salvarlos.
ㅤ    
ㅤ   
12- Dick llega al Hotel pero Jack lo deja inconsciente destruyendole la 
mandíbula con el mazo.

13- Jack persigue a Danny por el laberinto de arbustos y en un momento Danny le
grita que eso no es su padre entonces Jack recupera el control por un momento y
le dice a Danny que corra lo más rápido que pueda, que jamás lo olvide y
recuerda la caldera.
ㅤ    
ㅤ   
14- Jack corre a la caldera pero es demasido tarde, ante de poder activar la
palanca todo el Hotel explota.
ㅤ    
<center>
![Stephen King's original ending to "The Shining" featured the Overlook Hotel burning down thanks to a furnace [9]](https://arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/TY7RZQ4XVFLLKFVGFUEHDOLQKM.jpg){width=150% height=150%}
</center>
ㅤ   
Wendy había logrado escapar, Dick recupera la consciencia y los ayuda a 
escapar en su moto de nieve. Tiempo después, Halloran los ayuda a moverse a
Florida y le enseña a Danny algunas cosas sobre el resplandor [7].



</font>















